### ISSUE TITLE
Investigate intermittent update check failures

### ISSUE THREAD

**Issue by Splitwirez** [Splitwirez/Spore-Mod-Manager#15]
I've been seeing update checks fail intermittently in my Windows virtual machine. Not sure if running under WINE on my Kubuntu Linux host is affected yet.

Not sure if this is a bug or just my internet connection being god-awful...or possibly a combination of the latter and a virtualization-induced performance hit or something...

**Comment by VanillaCold** [comment]
I encountered this issue as well when launching Spore through the Mod Launcher a lot while testing a mod on my Windows 10 host machine, though I could still connect to Github in my web browser.

**Comment by Splitwirez** [comment]
Not an actual bug, seems this is just the product of some networking weirdness within my vmware VMs, or sometimes GitHub's automatic rate-limiting.
