### ISSUE TITLE
Mod branding not appearing in XML custom installers

### ISSUE THREAD

**Issue by VanillaCold** [Splitwirez/Spore-Mod-Manager#17]
In XML custom installers, the `.sporemod` file's Branding image should be used in the XML mod installer. 
This functionality is missing in the Spore Mod Manager.

**Comment by Splitwirez** [comment]
![image](https://user-images.githubusercontent.com/34009058/109871601-35e61180-7c20-11eb-8fff-1b6921176f3c.png)
