### ISSUE TITLE
Borderless Windowed setting no longer functions on 1.7.3.0

### ISSUE THREAD

**Issue by VanillaCold** [Splitwirez/Spore-Mod-Manager#33]
**Describe the bug**
When Spore is set to run as a borderless window in the Spore Mod Manager, it just runs as a regular window instead. The Override Window Mode setting still works for fullscreen and windowed mode, but it doesn't for borderless windowed mode.

**To Reproduce**
1. Go to Settings in the Spore Mod Manager
2. Enable "Override Window Mode"
3. Select "Borderless Windowed"
4. Launch Spore through the Spore Mod Manager.
5. Spore will launch as a regular, bordered window.

**Expected behavior**
Spore should instead start as a borderless window the size of the native screen resolution.

**Screenshots**
![image](https://user-images.githubusercontent.com/35960636/119540588-7e2b5080-bd85-11eb-92bc-c4c0c08f508d.png)

**Platform (please complete the following information):**
 - OS: Windows 10 Home (version 1909)
 - GPU: AMD Radeon R7 M440

**Additional context**
This bug didn't exist before the migration to .NET Core 3.1.

**Comment by Splitwirez** [comment]
Forgot to close this at the time, but this was fixed as of the 1.7.7.x builds.
